# Generated by Django 4.2.29 on 2026-03-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('stitching', 'In Stitching'), ('ready', 'Ready'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
